FROM python:3.10-alpine

WORKDIR /app

RUN apk update && apk add --no-cache git

COPY requirements/requirements-dev.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8080

CMD [ "python", "src/main.py" ]